#!/usr/bin/env bash
export MCD_CHAIN=testnet
export MCD_ILK=ETH
source lib/test

testJoin() {
  b1=$(./bin/mcd gem free)
  ./bin/mcd gem join $1
  b2=$(./bin/mcd gem free)
  assertBalanceChanged $b2 $b1 $1
}

testExit() {
  b1=$(./bin/mcd gem free)
  ./bin/mcd gem exit $1
  b2=$(./bin/mcd gem free)
  assertBalanceChanged $b1 $b2 $1
}

testLock() {
  b1=$(./bin/mcd gem locked)
  ./bin/mcd frob $1 0
  b2=$(./bin/mcd gem locked)
  assertBalanceChanged $b2 $b1 $1
}

testFree() {
  b1=$(./bin/mcd gem locked)
  ./bin/mcd frob -- -$1 0
  b2=$(./bin/mcd gem locked)
  assertBalanceChanged $b1 $b2 $1
}

testDraw() {
  b1=$(./bin/mcd dai balance)
  ./bin/mcd frob 0 $1
  b2=$(./bin/mcd dai balance)
  assertBalanceChanged $b2 $b1 $1
}

testWipe() {
  b1=$(./bin/mcd dai balance)
  ./bin/mcd frob -- 0 -$1
  b2=$(./bin/mcd dai balance)
  assertBalanceChanged $b1 $b2 $1
}

testJoin 1000
testLock 100
testDraw 400
testWipe 400
testFree 100
testExit 1000
