#!/usr/bin/env bash
export MCD_CHAIN=${MCD_CHAIN:-testnet}
source lib/test

testJoin() {
  echo "Test: join $1 --------------"
  lt=$(./bin/mcd gem balance vat)
  ./bin/mcd gem join $1
  gt=$(./bin/mcd gem balance vat)
  assertBalanceChanged $gt $lt $1
}

testExit() {
  echo "Test: exit $1 --------------"
  gt=$(./bin/mcd gem balance vat)
  ./bin/mcd gem exit $1
  lt=$(./bin/mcd gem balance vat)
  assertBalanceChanged $gt $lt $1
}

testLock() {
  echo "Test: lock $1 --------------"
  lt=$(./bin/mcd gem balance ink)
  ./bin/mcd frob $1 0
  gt=$(./bin/mcd gem balance ink)
  assertBalanceChanged $gt $lt $1
}

testFree() {
  echo "Test: free $1 --------------"
  lt=$(./bin/mcd gem balance vat)
  ./bin/mcd frob -- -$1 0
  gt=$(./bin/mcd gem balance vat)
  assertBalanceChanged $gt $lt $1
}

testDraw() {
  echo "Test: draw $1 --------------"
  lt=$(./bin/mcd dai balance vat)
  ./bin/mcd frob 0 $1
  gt=$(./bin/mcd dai balance vat)
  assertBalanceChanged $gt $lt $1
}

testWipe() {
  echo "Test: wipe $1 --------------"
  gt=$(./bin/mcd dai balance vat)
  ./bin/mcd frob -- 0 -$1
  lt=$(./bin/mcd dai balance vat)
  assertBalanceChanged $gt $lt $1
}

export MCD_ILK=ETH
testJoin 1000
testLock 100
testDraw 400
testWipe 400
testFree 100
testExit 1000

export MCD_ILK=REP
testJoin 1000
testLock 100
testDraw 400
testWipe 400
testFree 100
testExit 1000
