#!/usr/bin/env bash
### McDai - Multi-collateral Dai

OPTS="mcd [<options>] <command> [<args>]
mcd [<command>] --help
--
  Transaction Options:
F,from=address       account to send from
G,gas=number         number of gas units to provide
  Config Options:
C,config=            chain config - kovan (default), mainnet, or a setup file path
  MCD options:
I,ilk=address        ilk address
U,urn=address        urn address
  Filter options:
B,block=number       from block
"

set -e

if ! [[ $SETH_INIT ]]; then
  export SETH_INIT=1
  [[ -e ~/.sethrc ]] && . ~/.sethrc
fi

if [[ $2 = --help ]]; then
  exec "${0##*/}" help -- "$1"
elif [[ $1 = -* ]] && command -v "${0##*/}-$1" &>/dev/null; then
  exec "${0##*/}-$1" "${@:2}"
fi

eval "$(git rev-parse --parseopt -- "$@" <<<"$OPTS" || echo exit $?)"

while [[ $1 ]]; do
  case $1 in
    --)           shift; break;;

    -C|--config)  shift; export MCD_CONF=$1;;

    -I|--ilk)      shift; export MCD_ILK=$1;;
    -U|--urn)      shift; export MCD_URN=$1;;

    -B|--block)    shift; export ETH_BLOCK=$1;;

    -F|--from)    shift; export ETH_FROM=$1;;
    -G|--gas)     shift; export ETH_GAS=$1;;

    *) printf "${0##*/}: unrecognised option: %q\n" "--$1"; exit 1
  esac; shift
done

if [ ! -z $MCD_CONF ]; then
  case "$MCD_CONF" in
    kovan)
        export SETH_CHAIN=kovan
        export ETHERSCAN_API_URL=https://api-kovan.etherscan.io/api
      . ${0%/*}/conf/kovan;
    ;;
    mainnet)
      export SETH_CHAIN=mainnet
      export ETHERSCAN_API_URL=https://api.etherscan.io/api
      . ${0%/*}/conf/mainnet;
    ;;
    *)
      . $MCD_CONF;
    ;;
  esac
else
  export SETH_CHAIN=kovan
  export ETHERSCAN_API_URL=https://api-kovan.etherscan.io/api
  . ${0%/*}/conf/kovan
fi

"${0##*/}-${1-help}" "${@:2}"
