#!/usr/bin/env bash
set -e

if [[ -n "$MCD_PROXY" ]]; then
  mcd cdp-send-proxy "$@"
  exit
fi

case $1 in
  open) {
    ilk=$(mcd --require-ilk $0)
    guy=0x$(seth --to-word $ETH_FROM)
    tx=$(seth send --async ${CDP_MANAGER?} 'open(bytes32)' $ilk)
    echo >&2 -n "${0##*/}: Waiting for transaction receipt..."
    block=$(SETH_TICK=true seth receipt "$tx" blockNumber)
    block=$(seth --to-hex "$block")
    echo >&2
    sig="NewCdp(address,address,uint256)"
    sig=$(seth keccak "$(seth --from-ascii $sig)")
    logs=$(seth rpc eth_getLogs -- \
      -n {} \
        -s "${CDP_MANAGER?}" -i address \
        -s "$block"          -i fromBlock \
        -s "$block"          -i toBlock \
      -n [] \
        -s "$sig"  -i append \
        -s "$guy"  -i append \
      -i topics \
      -i append | echo "[$(paste -sd , -)]")
    hex=$(echo "$logs" | jshon -a -e data -u)
    echo "Opened: cdp $(seth --to-dec $hex)"
  };;
  give) {
    CDP=$(mcd --require-cdp mcd-cdp)
    sig="move(uint256,address)"
    to=$(mcd --to-address $2)
    seth send ${CDP_MANAGER?} $sig $CDP $to
  };;
  frob) {
    CDP=$(mcd --require-cdp mcd-cdp)
    dink=$(seth --to-uint256 $(mcd --to-hex $(seth --to-wei "$2 eth")))
    dart=$(seth --to-uint256 $(mcd --to-hex $(seth --to-wei "$3 eth")))
    sig="frob(address,uint,int,int)"
    seth send ${CDP_MANAGER?} $sig $MCD_VAT $CDP $dink $dart
    [[ $SETH_ASYNC != yes ]] && mcd urn
  };;
  dai) {
    # Aliases with cdp require
    CDP=$(mcd --require-cdp mcd-cdp)
    case $2 in
      join) { mcd dai join $3; };;
      exit) { mcd dai exit $3; };;
    esac
  };;
  gem) {
    CDP=$(mcd --require-cdp mcd-cdp)
    case $2 in
      join) { mcd gem join $3; };;
      exit) {
        [ -n "$3" ] || mcd --fail "cdp: Please specify an exit amount"
        sig="exit(address,uint256,address,uint256)"
        wad=$(seth --to-uint256 $(seth --to-hex $(seth --to-wei "$3 eth")))
        seth send ${CDP_MANAGER?} $sig $(mcd gem adapter) $CDP ${CDP_GUY?} $wad
        [[ $SETH_ASYNC != yes ]] && mcd gem balance
      };;
    esac
  };;
esac
