#!/usr/bin/env bash
### mcd-frobs -- Recent frobs
### Usage: mcd frobs [-B <block>]
set -e

abi="event Frob(bytes32 indexed ilk,bytes32 indexed urn,int256 dink,int256 dart);"
export SETH_ABI=$(seth abi "$abi")
seth events $MCD_PIT
