#!/usr/bin/env bash
### mcd-urn -- Get urn state
### Usage: mcd urn --ilk=<id> [--urn=<address>]
###
### Display the status of the urn at ETH_FROM or
### at a given urn address if provided.
set -e

[ ! -z "$MCD_ILK" ] || mcd --fail "$0: An ilk identifier is required"

ilk=$(seth --to-bytes32 $(seth --from-ascii "$MCD_ILK"))
lad=$(seth --to-checksum-address ${MCD_URN:-$ETH_FROM})
echo "ilk: $MCD_ILK";
echo "lad: $lad";
lad=$(seth --to-word $lad)

gem=$(seth call "${MCD_VAT}" 'gem(bytes32,bytes32)(uint256)' "$ilk" "$lad")
echo "gem: $(mcd rad ${gem})"

urn=$(seth call "${MCD_VAT}" 'urns(bytes32,bytes32)(uint256,uint256)' "$ilk" "$lad")
echo "ink: $(mcd wad ${urn:0:64})"
echo "art: $(mcd wad ${urn:65:129})"
