#!/usr/bin/env bash
### mcd-ilk -- Show ilk state
### Usage: mcd ilk <id>
set -e
[ $# = 1 ] || mcd --fail "$0: Bad argument(s)"

ilk=$(seth --to-bytes32 $(seth --from-ascii "$1"))
vat=$(seth call $MCD_VAT 'ilks(bytes32)(uint256, uint256, uint256, uint256)' $ilk)
echo "take: $(mcd ray ${vat:0:64})"
echo "rate: $(mcd ray ${vat:65:64})"
echo "Ink:  $(mcd wad ${vat:130:64})"
echo "Art:  $(mcd wad ${vat:195:64})"
