#!/usr/bin/env bash
set -e

case $MCD_ILK in
  "ETH") {
    adapter=$MCD_JOIN_ETH
  };;
  "REP") {
    adapter=$MCD_JOIN_REP
  };;
  *) {
    mcd --fail "gem: Unrecognised adapter $MCD_ILK"
  }
esac

wad=$(seth --to-word $(seth --to-wei $1 eth))
(set -x; seth send $adapter "exit(address, uint)" $ETH_FROM $wad)
