#!/usr/bin/env bash
### mcd-dai -- Dai balances
### Usage: mcd dai [<command>]
set -e

case $1 in
  balance) {
    urn=$(seth --to-word ${2:-$ETH_FROM})
    bal=$(seth call $MCD_VAT 'dai(bytes32)(uint256)' "$urn")
    echo $(mcd --to-rad $bal)
  };;
  supply) {
    mcd debt
  };;
  move) {
    echo "Not implemented"
  };;
  hope) {
    echo "Not implemented"
  };;
  nope) {
    echo "Not implemented"
  };;
  *) {
    echo "Options:"
    echo "  balance [<address>]"
    echo "  hope <address>"
    echo "  move <src> <dst>"
    echo "  nope <address>"
    echo "  supply"
  }
esac
