#!/usr/bin/env bash
### mcd-exit -- Remove collateral from the system
### Usage: mcd exit <ilk> <wad>
###    or: mcd exit <address> <wad>
###
### Specify either an ilk identifier or an adapter address
### and the amount of collateral to withdraw.
###
### Example: mcd exit ETH 42
set -e
[ $# = 2 ] || mcd --fail "$0: Missing argument(s)"

case $1 in
  "ETH") {
    adapter=$MCD_JOIN_ETH
  };;
  *) {
    adapter=$(mcd --to-address $1) || mcd --fail "$0: Unrecognised adapter $1"
  }
esac

wad=$(seth --to-word $(seth --to-wei $2 eth))
(set -x; seth send $adapter "exit(address, uint)" $ETH_FROM $wad)
