#!/usr/bin/env bash
set -e
[ -n "$1" ] || mcd --fail "mcd-dai: Please specify an exit amount"
usr="$(mcd --to-address "${2:-$ETH_FROM}")"

mcd --vat-hope "${MCD_JOIN_DAI?}"

wad="$(seth --to-word "$(seth --to-wei "$1" eth)")"
sig="exit(address usr, uint256 wad)"
seth send "$MCD_JOIN_DAI" "$sig" "$usr" "$wad"

[[ $SETH_ASYNC != yes ]] && mcd dai balance
