#!/usr/bin/env bash
### mcd-dai -- Dai management
### Usage: mcd [--urn=<index>] dai [<command>]
###
### Commands: dai balance    Print balances for a given urn (default: ETH_FROM)
###           dai supply     Get the total supply
###           dai join <wad> Exchange DSToken Dai for Vat Dai
###           dai exit <wad> Exchange Vat Dai for DSToken Dai
###
### Example:  mcd dai balance
###           mcd dai join 72.50
set -e

mcd-dai-cmd() {
  mcd --require-urn $0 &>/dev/null
  exec 5< <(mcd dai $1 vat)
  exec 6< <(mcd dai $1 ext)
  echo "vat $(cat <&5) Vat Dai $1"
  echo "ext $(cat <&6) ERC20 Dai $1"
}

case $1 in
  balance) {
    case $2 in
      vat)   {
        urn=$(mcd --require-urn $0)
        sig="dai(address)(uint256)"
        mcd --to-rad $(seth call ${MCD_VAT?} $sig $urn)
      };;
      ext) {
        sig="balanceOf(address)(uint)"
        mcd --to-wad $(seth call ${MCD_DAI?} $sig $ETH_FROM)
      };;
      "")  { mcd-dai-cmd balance; };;
      *)   { mcd dai balance;     };;
    esac
  };;
  supply) {
    case $2 in
      vat)   { echo $(mcd debt); };;
      ext) {
        sig="totalSupply()(uint)"
        mcd --to-wad $(seth call "$MCD_DAI" $sig)
      };;
      "")  { mcd-dai-cmd supply; };;
      *)   { mcd dai supply;     };;
    esac
  };;
  join) { exec mcd-dai-join $2;    };;
  exit) { exec mcd-dai-exit $2 $3; };;
  *)    { mcd help dai;            }
esac
