#!/usr/bin/env bash
### mcd-bite -- Trigger liquidation of an unsafe urn
### Usage: mcd bite --ilk=<id> --urn=<address> bite
###
### Specify the Ilk identifier and owner address of
### the Urn to bite.
set -e

[ ! -z "$MCD_ILK" ] &&
[ ! -z "$MCD_URN" ] ||
mcd --fail "$0: Missing argument(s)"

ilk=$(seth --to-bytes32 $(seth --from-ascii "$MCD_ILK"))
urn=$(seth --to-bytes32 $MCD_URN)

(set -x; seth send "${MCD_CAT}" "bite(bytes32,bytes32)(uint256)" "$ilk" "$urn")
