#!/usr/bin/env bash
### mcd-bites -- View bites and trigger flip auctions
### Usage: mcd bites <id>
###    or: mcd bites flip <id> <wad>
set -e

shopt -s extglob
case "$1" in
  +([[:digit:]])) {
    mcd bites-get "$1"
  };;
  flip) {
    [ $# = 3 ] || mcd --fail "$0: Incorrect arguments"
    n=$(seth --to-word $(seth --to-hex $2))
    w=$(seth --to-word $(seth --to-hex $(seth --to-wei "$3 eth")))
    mcd bites-flip "$n" "$w"
  };;
  *) {
    mcd bites-ls "$@"
  }
esac
