#!/usr/bin/env bash
### mcd-urn -- Show urn state
### Usage: mcd urn --ilk=<id> [--urn=<address>]
###
### Display the status of the urn at ETH_FROM or
### at a given urn address if provided.
set -e

[ ! -z "$MCD_ILK" ] || mcd --fail "$0: An ilk identifier is required"

ilk=$(seth --to-bytes32 $(seth --from-ascii "$MCD_ILK"))
urn=$(seth --to-checksum-address ${MCD_URN:-$ETH_FROM})
echo "lad: $urn"
urn=$(seth --to-bytes32 $urn)

res=$(seth call "${MCD_VAT}" 'urns(bytes32,bytes32)(uint256,uint256)' "$ilk" "$urn")
echo "ink: $(mcd wad ${res:0:64})"
echo "art: $(mcd wad ${res:65:129})"
