#!/usr/bin/env bash
set -e
ilk=$(mcd --get-ilk)
urn=$(mcd --get-urn gem)
gem=$(mcd gem symbol)
case $1 in
  vat) {
    sig="gem(bytes32,address)(uint256)"
    mcd --to-wad $(seth --to-hex $(seth call ${MCD_VAT?} "$sig" "$ilk" "$urn"))
  };;
  ink) { mcd --ilk=${MCD_ILK} urn ink; };;
  ext) {
    sig="balanceOf(address)(uint256)"
    mcd --to-wad $(seth --to-hex $(seth call $(mcd gem address) "$sig" "$ETH_FROM"))
  };;
  "")   {
    exec 3< <(mcd gem balance vat)
    exec 4< <(mcd gem balance ink)
    exec 5< <(mcd gem balance ext)
    echo "vat $(cat <&3) Unlocked collateral ($gem)"
    echo "ink $(cat <&4) Locked collateral ($gem)"
    echo "ext $(cat <&5) External account balance ($gem)"
    if [[ "$gem" == "WETH" ]]; then
      eth=$(mcd --to-wad $(seth --to-hex $(seth balance $ETH_FROM)))
      echo "eth $eth External account balance (ETH)"
      echo
    fi
  };;
  *)   { mcd gem balance; };;
esac
