#!/usr/bin/env bash
set -e
dst=$(seth --to-address $1)

approve() {
  (set -x; seth send "$MCD_VAT" "hope(address)" $dst)
}

prompt() {
  echo "Vat move: Approval required."
  echo "src: $ETH_FROM (ETH_FROM)"
  echo "dst: $dst"
  read -r -p "Grant approval to move Dai [Y/n]: " response
  case $response in
    [yY]) { approve; };;
    *)    { exit 1; };;
  esac
}

sig="can(address,address)"
can=$(seth call "${MCD_VAT?}" "$sig" $ETH_FROM $dst)
if [[ $(seth --to-dec $can) -ne 1 ]]; then
  [[ $SETH_ASYNC != yes ]] && prompt || approve
fi
