#!/usr/bin/env bash
### mcd-flop -- Trigger a flop auction
### Usage: mcd flop
###
### Trigger a flop auction if there is sufficient
### bad-debt (Woe) awaiting auction.
set -e

exec 3< <(mcd vow Woe)
exec 4< <(mcd vow Joy)
exec 5< <(mcd vow sump)

woe=$(cat <&3)
joy=$(cat <&4)
sump=$(cat <&5)

if (( $(echo "$joy > 0" | bc -l) )); then
  echo "Fail: Joy ($joy) is not zero"
  echo "Hint: mcd heal $joy"
  exit 1
fi

if (( $(echo "$woe < $sump" | bc -l) )); then
  echo "Fail: Insufficient Woe ($woe)"
  echo "Hint: mcd flog <timestamp>"
  exit 1
fi

(set -x; seth send "${MCD_VOW}" "flop()")
