#!/usr/bin/env bash
set -e
[ -n "$1" ] || mcd --fail "mcd-gem: Please specify an exit amount"

mcd --require-ilk

gem="$(mcd gem address)"
exit="$(mcd gem adapter)"
decimals="$(mcd gem decimals)"

amount="$(printf "%.0f" "$(echo "$1 * 10^$decimals" | bc)")"

urn="$(mcd --get-urn "$gem")"

wad="$(seth --to-uint256 "$amount")"
sig="exit(address, uint256)"
seth send "$exit" "$sig" "$urn" "$wad"

[[ $SETH_ASYNC != yes ]] && mcd gem balance
