#!/usr/bin/env bash
### mcd-exit -- Remove collateral from the system
### Usage: mcd exit <adapter> <amount>
###
### Specify the @adapter and amount of collateral
### to withdraw.
set -e
[ $# = 2 ] || mcd --fail "$0: Missing argument(s)"

addr=$(mcd --to-address $1) || mcd --fail "$0: Invalid adapter $1"
wad=$(seth --to-word $(seth --to-wei $2 eth))
(set -x; seth send $addr "exit(address, uint)" $ETH_FROM $wad)
