#!/usr/bin/env bash
### mcd-flops -- Flop auction management
### Usage: mcd flops [<id>] [<command>]
###
### Commands: ls                    List recent flop auctions
###           beg                   Minimum bid increase
###           pad                   Lot increase for tick
###           ttl                   Max bid lifetime
###           end                   Max auction duration
###           count                 Total auction count
###           <id>                  View auction status
###           <id> dent <lot> <bid> Submit a bid (decreasing lot amount)
###           <id> deal             Settle
set -e
shopt -s extglob

case $1 in
  ls) {
    export ETH_BLOCK=${ETH_BLOCK:-$(mcd --from-block)}
    sig="Kick(uint256,uint256,uint256,address)"
    sig=$(seth keccak "$(seth --from-ascii $sig)")
    seth logs "${MCD_FLOP?}" "$sig" |
      while read -r log; do
        tx=$(jshon -e transactionHash -u <<<"$log")
        block=$(seth --to-dec "$(jshon -e blockNumber -u <<<"$log")")
        topics=($(jshon -e topics -a -u <<<"$log"))
        data=$(jshon -e data -u <<<"$log")

        echo "id $(seth --to-dec "${data:2:64}")"
        echo "lot $(mcd --to-wad "${data:66:64}")"
        echo "bid $(mcd --to-rad "${data:130:64}")"
        echo "gal 0x${topics[1]:26:64}"
        echo "tx: $tx";
        echo "block: $block";
        echo
      done
  };;
  beg) {
    mcd --to-wad "$(seth call "${MCD_FLOP?}" 'beg()')"
  };;
  pad) {
    mcd --to-wad "$(seth call "${MCD_FLOP?}" 'pad()')"
  };;
  ttl) {
    seth --to-dec "$(seth call "${MCD_FLOP?}" 'ttl()')"
  };;
  tau) {
    seth --to-dec "$(seth call "${MCD_FLOP?}" 'tau()')"
  };;
  count) {
    seth --to-dec "$(seth call "${MCD_FLOP?}" 'kicks()')"
  };;
  +([[:digit:]]) ) {
    mcd-flops-cmd "${@}"
  };;
  *) {
    mcd help flops
  };;
esac
