#!/usr/bin/env bash
### mcd-wrap -- Wrap ETH to WETH
### Usage: mcd wrap <amount>
set -e
mcd --require-from "$0"
[ -n "$1" ] || mcd --fail "mcd-wrap: Please specify an amount to wrap"
seth send "${ETH?}" --value "$(seth --to-wei "$1 eth")"

[[ $SETH_ASYNC == yes ]] && exit 1

sig="balanceOf(address)(uint)"
weth="$(seth --to-fix 18 "$(seth call "${ETH?}" "$sig" "$ETH_FROM")")"
eth=$(seth --to-fix 18 "$(seth balance "$ETH_FROM")")

echo "eth  $eth"
echo "weth $weth"
