#!/usr/bin/env bash
set -e
case $MCD_ILK in
  "ETH") {
    curl -sS 'http://api.etherscan.io/api?module=stats&action=ethsupply' |
      seth --to-fix 18 $(jq -r '.result')
  };;
  *) {
    gem=$(seth call $(mcd gem adapter) 'gem()')
    sig="totalSupply()(uint)"
    mcd --to-wad $(seth call "${gem:(-40)}" $sig)
  };;
esac
