#!/usr/bin/env bash
set -e
gem=$(mcd gem address)
dst=$(seth --to-address "$1")
amt=$2

approve() {
  max="0x$(printf "f"'%.0s' {1..64})"  # uint(-1)
  (set -x; seth send "$gem" "approve(address,uint)" "$dst" "$max")
}

prompt() {
  sym=$(mcd gem symbol)
  echo "$sym: Insufficient allowance."
  echo "src: $ETH_FROM (ETH_FROM)"
  echo "dst: $dst"
  read -r -p "Grant approval to move $sym [Y/n]: " response
  case $response in
    [yY]) { approve; };;
    *)    { exit 1; };;
  esac
}

sig="allowance(address,address)(uint256)"
allowance="$(seth call "${MCD_DAI?}" "$sig" "$ETH_FROM" "$dst")"
if (( $(echo "$amt > $allowance" | bc -l) )); then
  [[ $SETH_ASYNC != yes ]] && prompt || approve
fi
