#!/usr/bin/env bash
set -e
ilk=$(mcd --get-ilk)
urn=$(mcd --get-urn gem)
gem=$(mcd gem symbol)
case $1 in
  vat) {
    sig="gem(bytes32,address)"
    gem="$(seth call "${MCD_VAT?}" "$sig" "$ilk" "$urn")"
    mcd --to-wad "$gem"
  };;
  ink) { mcd --ilk="${MCD_ILK}" urn ink; };;
  ext) {
    sig="balanceOf(address)(uint256)"
    decimals=$(mcd gem decimals)
    balance=$(seth call "$(mcd gem address)" "$sig" "$ETH_FROM")
    seth --to-fix "${decimals?18}" "$balance"
  };;
  "")   {
    exec 3< <(mcd gem balance vat)
    exec 4< <(mcd gem balance ink)
    echo "vat $(cat <&3) Unlocked collateral ($gem)"
    echo "ink $(cat <&4) Locked collateral ($gem)"
    if [[ ! -z "$ETH_FROM" ]]; then
      exec 5< <(mcd gem balance ext)
      echo "ext $(cat <&5) External account balance ($gem)"
      if [[ "$gem" == "WETH" ]]; then
        eth=$(mcd --to-wad "$(seth --to-hex "$(seth balance "$ETH_FROM")")")
        echo "eth $eth External account balance (ETH)"
        echo
      fi
    fi
  };;
  *)   { mcd gem balance; };;
esac
