#!/usr/bin/env bash
set -e
[[ $MCD_VAT_ILK ]] ||
  MCD_VAT_ILK=$(seth call "${MCD_VAT?}" 'ilks(bytes32)(uint256, uint256, uint256, uint256, uint256)' "$1")
  export MCD_VAT_ILK
echo $MCD_VAT_ILK   # no shellcheck
