#!/usr/bin/env bash
set -e
[[ $MCD_SPOT_ILK ]] ||
  MCD_SPOT_ILK=$(seth call "${MCD_SPOT?}" 'ilks(bytes32)(address, uint256)' "$1"); # no shellcheck
  export MCD_SPOT_ILK
echo $MCD_SPOT_ILK  # no shellcheck
