#!/usr/bin/env node

var BN   = require('bn.js');
var lpad = (x, y, n) => repeat(y, n - x.length) + x;
var repeat = (x, n) => n > 0 ? new Array(n + 1).join(x) : "";
var toHex = x => new BN(x, 10).toTwos(8).toString(16);

console.log(`0x${lpad(toHex(process.argv[2]), "0", 64)}`);
