#!/usr/bin/env bash
### mcd-flog -- Release queued bad-debt for auction
### Usage: mcd flog <timestamp>
###
### Specify the timestamp of the debt in the queue to release it
### for auction. Queued debt will only be released once the wait
### time has elapsed.
set -e

[ $# = 1 ] || mcd --fail "$0: A timestamp is required"

# TODO
# timestamp parsing
# list all items in the debt queue

era="$1"

(set -x; seth send "${MCD_VOW}" "flog(uint48)" $era)
