#!/usr/bin/env bash
set -e

missing-deployment() {
cat <<.
Please specify which mcd deployment you wish to target:
  For example, try running against the latest kovan
  deployment by settig the chain option:
  mcd --chain=kovan <command>
You could also try running against a remote testnet:
  List available testnets with: \`mcd testnet chains'
  and then set the chain option to a testnet id:
  mcd --chain=12899149080555595289 <command>
You can also specify a path to a custom address config
file when runing against deployments on a local testnet:
  mcd --config=path/to/out.addresses.json <command>
For more options see \`mcd help'.
.
}

[ -n "$MCD_VAT" ] || missing-deployment

missing-ilk() {
cat >&2 <<.
Error: missing Ilk identifier

You must specify an Ilk (collateral type) using the --ilk=<id> option.
See \`mcd ilks' for a list of approved collateral types.
.
exit 1
}

invalid-ilk() {
cat >&2 <<.
Error: invalid Ilk identifier

The Ilk identifier $MCD_ILK is not a recognised collateral type.
See \`mcd ilks' for a list of approved collateral types.
.
exit 1
}

valid-ilks() {
  echo $(mcd ilks | cut -d ' ' -f 1)
}

[ -n "$MCD_ILK" ] || missing-ilk

valid-ilks | grep -qE "\s$MCD_ILK\s|\s$MCD_ILK$" || invalid-ilk
