#!/usr/bin/env bash
set -e
[ -n "$1" ] || mcd --fail "mcd-dai: Please specify a join amount"

urn=$(mcd --get-urn dai)
wad=$(seth --to-uint256 "$(seth --to-wei "$1" eth)")

mcd --dai-approve "$MCD_JOIN_DAI" "$wad"

seth send "$MCD_JOIN_DAI" "join(address, uint)" "$urn" "$wad"

[[ $SETH_ASYNC != yes ]] && mcd dai balance
