#!/usr/bin/env bash
set -e
if [[ $1 = @* ]]; then
  name="MCD_${1#@}"
  name=$(tr "[:lower:]" "[:upper:]" <<<"$name")
  name=${name//-/_}
  [[ ${!name} ]] || mcd --fail "${0##*/}: error: not found: $name";
  [[ ${!name} ]] && seth --to-address "${!name}";
else
  lad=${1#0x}
  lad=${lad::40}
  seth --to-address "$lad"
fi
