#!/usr/bin/env bash
set -e
case $1 in
  exit) {
    [ -n "$2" ] || mcd --fail "mcd-cdp: Please specify a dai amount"
    wad=$(seth --to-uint256 $(seth --to-hex $(seth --to-wei "$2 eth")))
    if [[ $MCD_PROXY == yes ]]; then
      sig="exit(address,address,uint,address,uint)"
      mcd --proxy-exec $sig $CDP_MANAGER $MCD_JOIN_DAI $CDP $ETH_FROM $wad
    else
      sig="exit(address,uint,address,uint)"
      seth send ${CDP_MANAGER?} $sig $MCD_JOIN_DAI $CDP $ETH_FROM $wad
    fi
    [[ $SETH_ASYNC != yes ]] && mcd dai balance
  };;
  *) {
    mcd dai "$@";
  };;
esac
