#!/usr/bin/env bash
### mcd-flap -- Trigger a flap auction
### Usage: mcd flap
###
### Trigger a flap auction if sufficient surplus Dai (Joy)
### has accumulated in the liquidator.
set -e

exec 3< <(mcd vow Woe)
exec 4< <(mcd vow Joy)
exec 5< <(mcd vow Awe)
exec 6< <(mcd vow pad)
exec 7< <(mcd vow lump)

woe=$(cat <&3)
joy=$(cat <&4)
awe=$(cat <&5)
pad=$(cat <&6)
lump=$(cat <&7)

req=$(bc <<< "($awe + $lump) + $pad")

if (( $(echo "$woe > 0" | bc -l) )); then
  echo "Fail: Woe ($woe) is not zero"
  exit 1
fi

if (( $(echo "$joy < $req" | bc -l) )); then
  echo "Fail: Insufficient Joy ($joy)"
  exit 1
fi

(set -x; seth send "${MCD_VOW}" "flap()")
