#!/usr/bin/env bash
### mcd-frobs -- Recent frobs
### Usage: mcd frobs [-B <block>] [--ilk=<id>] [--urn=<address>]
set -e
export ETH_BLOCK=${ETH_BLOCK:-$(mcd --from-block)}
sig=$(seth --to-bytes32 "7cdd3fde")
[[ "$MCD_ILK" ]] && ilk=$(seth --to-bytes32 $(seth --from-ascii "$MCD_ILK"))
[[ "$MCD_URN" ]] && urn=$(seth --to-bytes32 "$MCD_URN")
seth logs ${MCD_VAT?} $sig $ilk $urn |
  while read -r log; do
    tx=$(jshon -e transactionHash -u <<<"$log")
    block=$(seth --to-dec $(jshon -e blockNumber -u <<<"$log"))
    topics=($(jshon -e topics -a -u <<<"$log"))
    data=$(jshon -e data -u <<<"$log")
    data=${data:138:256} # ilk, usr, dink, dart

    echo "ilk $(mcd --to-ascii ${topics[1]})"
    echo "urn 0x${topics[2]:(-40)}"
    echo "dink $(mcd --to-wad ${data:128:64})"
    echo "dart $(mcd --to-wad ${data:192:64})"
    echo "tx: $tx";
    echo "block: $block";
    echo
  done
