#!/usr/bin/env bash
p() {
  b32=$(seth --to-bytes32 $(seth --from-ascii "$1"))
  printf "%-4s %-64s %-22s\n" "$1" "$b32" "$2";
}

p "ETH"  "Ethereum"
p "REP"  "Augur"
p "GUSD" "Gemini dollar"
p "USDC" "USD Coin"
p "ZRX"  "0x"
p "OMG"  "OmiseGo"
p "BAT"  "Basic Attention Token"
p "DGD"  "Digix Gold"
p "GNT"  "Gnosis"
