#!/usr/bin/env bash
### mcd-poke -- Update the price feed for a given Ilk
### Usage: mcd --ilk=<id> poke
###
### Specify either an ilk identifier or a feed address
###
### Example: mcd poke ETH
set -e

[ ! -z "$MCD_ILK" ] || mcd --fail "$0: Missing Ilk identifier"
ilk=$(seth --to-bytes32 $(seth --from-ascii "$MCD_ILK"))
pip=$(eval echo "\$PIP_${MCD_ILK}")

echo "Poke the pip:"
tx=$(set -x; seth send --async $pip "poke()")

echo "Poke the spotter:"
(set -x; seth send $MCD_SPOT "poke()")

echo "$MCD_ILK spot: $(mcd --ilk=$MCD_ILK ilk spot)"
