#!/usr/bin/env bash
set -e
[ -n "$1" ] || mcd --fail "mcd-gem: Please specify a join amount"

mcd --require-ilk

gem=$(mcd gem address)
join=$(mcd gem adapter)

mcd --gem-approve $join $1

urn=$(mcd --get-urn gem)
wad=$(seth --to-uint256 $1)
seth send "$join" "join(address, uint)" $urn $wad

[[ $SETH_ASYNC != yes ]] && mcd gem balance
