#!/usr/bin/env bash
set -e
[ -n "$1" ] || mcd --fail "mcd-gem: Please specify a join amount"

mcd --require-ilk

gem="$(mcd gem address)"
join="$(mcd gem adapter)"
decimals="$(mcd gem decimals)"
amount="$(echo "$1 * 10^$decimals" | bc)"

mcd --gem-approve "$join" "$amount"

urn="$(mcd --get-urn "$gem")"

seth send "$join" "join(address, uint256)" "$urn" "$amount"

[[ $SETH_ASYNC != yes ]] && mcd gem balance
