#!/usr/bin/env bash
set -e
p() { printf "%-3s %-50s %-10s\n" "$1" "$2" "$3"; }

sig="flip(uint256,uint256)(uint256)"
tx=$(seth send --async -G 200000 "${MCD_CAT?}" $sig "$1" "$2")
echo >&2 -n "${0##*/}: Waiting for transaction receipt..."
block=$(SETH_TICK=true seth receipt "$tx" blockNumber)
block=$(seth --to-hex "$block")
echo >&2

sig="FlipKick(uint256,uint256)"
keccak=$(seth keccak "$(seth --from-ascii $sig)")
logs=$(seth rpc eth_getLogs -- \
  -n {} \
    -s "${MCD_CAT?}" -i address \
    -s "$block"      -i fromBlock \
    -s "$block"      -i toBlock \
  -n [] \
    -s "$keccak" -i append \
  -i topics \
  -i append | echo "[$(paste -sd , -)]")
data=$(echo "$logs" | jshon -a -e data -u)
hash=$(echo "$logs" | jshon -a -e transactionHash -u)

if [ "$hash" == "$tx" ]; then
  echo "$tx"
  mcd flips $(seth --to-dec $1)
  echo
  echo "flip auction id: $(seth --to-dec ${data:(-64)})"
else
  echo >&2 "${0##*/}: Transaction failed."
  seth >&2 receipt "$tx"
  exit 1
fi
