#!/usr/bin/env bash
set -e
case $MCD_ILK in
  "ETH") {
    wei=$(seth balance "$(mcd gem adapter)")
    mcd --to-wad "$wei"
  };;
  *) {
    gem="$(seth call "$(mcd gem adapter)" 'gem()(address)')"
    sig="balanceOf(address)(uint256)"
    decimals=$(mcd gem decimals)
    balance=$(seth call "$gem" "$sig" "$(mcd gem adapter)")
    seth --to-fix "${decimals?18}" "$balance"
  };;
esac
