#!/usr/bin/env bash
### mcd-frob -- CDP management
### Usage: mcd [<options>] frob <dink> <dart>
set -e
[ $# = 2 ] || mcd frob --fail

# TODO check & handle +- inputs
# TODO lock | free | draw| wipe wrappers?

echo "Updating CDP..."
echo "Setting ink to ink + $dink"
echo "Setting art to art + $dart"

dink=$(seth --to-hex $(seth --to-wei "$1 eth"))
dart=$(seth --to-hex $(seth --to-wei "$2 eth"))

(set -x; seth send "${MCD_PIT?}" "frob(bytes32,int,int)" "$MCD_ILK" "$dink" "$dart")
