#!/usr/bin/env bash
cat <<.
BTC   Bitcoin
ETH   Ethereum
XRP   Ripple
EOS   EOS
LTC   Litecoin
BCH   Bitcoin Cash
USDT  Tether
XLM   Stellar
TRX   Tron
BNB   Binance
ADA   Cardano
XMR   Monero
EOS   IOTA
DAS   Dash
NEO   Neo
ETC   Ethereum Classic
XEM   NEM
ONT   Ontology
ZEC   Zcash
WAVES Waves
XTZ   Tezos
VET   VeChain
DOGE  Dogecoin
USDC  USD Coin
BTG   Bitcoin Gold
TUSD  TrueUSD
QTUM  Qtum
OMG   OmiseGO
BAT   Basic Attention Token
LINK  Chainlink
HOT   Holo
DCR   Decred
ZIL   Zilliqa
REP   Augur
ZRX   0x
LSK   Lisk
BTS   BitShares
BCN   Bytecoin
DGB   DigiByte
BCD   Bitcoin Diamond
ICX   ICON
NANO  Nano
PAX   Paxos Standard Token
NPXS  Pundi X
KMD   Komodo
STEEM Steem
AE    Aeternity
SC    Siacoin
S4F   S4FE
GUSD  Gemini Dollar
GNT   Golem Golem
R     Revain
ARK   Ark
HT    Huobi Token
MAID  MaidSafeCoin
FCT   Factom
ARDR  Ardor
.
