#!/usr/bin/env bash
### vow sin -- Get queued sin amount at a given era
### Usage: mcd vow sin <era>
###
### Where <era> is the block timestamp of a bite.
### Returns zero if queued debt has been released for auction.
set -e
[ $# = 1 ] || mcd --fail "$0: Bad argument(s)"

era="$1"
sin=$(seth call $MCD_VOW 'sin(uint256)(uint256)' "$era")
mcd --to-wad "$sin"
