#!/usr/bin/env bash
### mcd-frob -- Urn management
### Usage: mcd frob --ilk=<id> [--urn=<index>] -- [-]<dink> [-]<dart>
set -e
[ $# = 2 ] || mcd --fail "$0: Incorrect arguments"

ilk=$(mcd --require-ilk)
urn=$(mcd --require-urn $0)

dink=$(seth --to-uint256 $(mcd --to-hex $(seth --to-wei "$1 eth")))
dart=$(seth --to-uint256 $(mcd --to-hex $(seth --to-wei "$2 eth")))
sig="frob(bytes32, address, address, address, int, int)"
seth send ${MCD_VAT?} "$sig" "$ilk" "$urn" "$urn" "$urn" "$dink" "$dart"

[[ $SETH_ASYNC != yes ]] && mcd urn
