#!/usr/bin/env bash
### mcd-flog -- Release queued bad-debt for auction
### Usage: mcd flog <timestamp>
###
### Specify a sin-queue timestamp to release debt for auction.
### Queued debt will only be released if the wait time has elapsed.
###
### See also mcd-vow
set -e

[ $# = 1 ] || mcd --fail "$0: A timestamp is required"

# TODO
# timestamp parsing
# list all items in the debt queue

era="$1"

(set -x; seth send "${MCD_VOW}" "flog(uint48)" $era)
