#!/usr/bin/env bash
### mcd-dai -- Dai management
### Usage: mcd [--urn=<id>] dai [<command>]
###
### Commands: dai balance    Print balances for a given urn (default: ETH_FROM)
###           dai supply     Get the total supply
###           dai join <wad> Exchange DSToken Dai for Vat Dai
###           dai exit <wad> Exchange Vat Dai for DSToken Dai
###
### Example:  mcd dai balance
###           mcd dai join 72.50
set -e

mcd-dai-cmd() {
  exec 5< <(mcd dai $1 vat)
  exec 6< <(mcd dai $1 ext)
  echo "vat $(cat <&5) Vat $1"
  echo "ext $(cat <&6) ERC20 $1"
}

case $1 in
  address) {
    case $2 in
      vat) { echo ${MCD_VAT?};    };;
      ext) { echo ${MCD_DAI?};    };;
      "")  { mcd-dai-cmd address; };;
      *)   { mcd dai address;     };;
    esac
  };;
  balance) {
    urn=$(mcd --require-urn $0)
    case $2 in
      vat)   {
        sig="dai(bytes32)(uint256)"
        mcd --to-rad $(seth call ${MCD_VAT?} $sig $urn)
      };;
      ext) {
        sig="balanceOf(address)(uint)"
        mcd --to-wad $(seth call ${MCD_DAI?} $sig $(seth --to-address ${urn::40}))
      };;
      "")  { mcd-dai-cmd balance; };;
      *)   { mcd dai balance;     };;
    esac
  };;
  supply) {
    case $2 in
      vat)   { echo $(mcd debt); };;
      ext) {
        sig="totalSupply()(uint)"
        mcd --to-wad $(seth call "$MCD_DAI" $sig)
      };;
      "")  { mcd-dai-cmd supply; };;
      *)   { mcd dai supply;     };;
    esac
  };;
  join) {
    urn=$(mcd --require-urn $0)
    lad=$(mcd --to-address $urn)
    wad=$(seth --to-word $(seth --to-wei $2 eth))
    sig="join(bytes32, uint256)"
    (set -x; seth send $MCD_JOIN_DAI "$sig" $urn $wad)
    mcd dai balance
  };;
  exit) {
    urn=$(mcd --require-urn $0)
    lad=$(mcd --to-address $urn)
    wad=$(seth --to-word $(seth --to-wei $2 eth))
    sig="exit(bytes32, address, uint256)"
    (set -x; seth send $MCD_JOIN_DAI "$sig" $urn $lad $wad)
    mcd dai balance
  };;
  *)  { mcd help dai; }
esac
