#!/usr/bin/env bash
set -e

gem=$(mcd gem address)
dst=$1
amt=$2

approve() {
  max="0x$(printf "f"'%.0s' {1..64})"
  seth send "$gem" "approve(address,uint)" $dst $max
}

sig="allowance(address,address)(uint)"
wad=$(seth call "$gem" "$sig" $ETH_FROM $dst)
wad=$(mcd --to-wad $(seth --to-dec $wad))
if (( $(echo "$amt > $wad" | bc -l) )); then
  echo "Insufficient allowance: ETH_FROM: $ETH_FROM"
  read -r -p "Grant approval to move $(mcd gem symbol) to $dst? [Y/n]: " response
  case $response in
    [yY]) { approve; };;
    *)    { exit 1; };;
  esac
fi
