#!/usr/bin/env bash
urn=$(mcd --require-urn $0)
guy=$(mcd --to-address ${2:-$ETH_FROM})
wad=$(seth --to-word $(seth --to-wei $1 eth))
sig="exit(bytes32, address, uint256)"
seth send $MCD_JOIN_DAI "$sig" $urn $guy $wad
[[ $SETH_ASYNC != yes ]] && mcd dai balance
