#!/usr/bin/env bash
set -e

if [ ! -z "$MCD_ILK" ]; then
  ilk=0x$(seth --to-bytes32 $(seth --from-ascii "$MCD_ILK"))
  topics="-s $2 -i append -s $ilk -i append"
else
  topics="-s $2 -i append"
fi

if [ ! -z "$ETH_BLOCK" ]; then
  ETH_BLOCK=$(seth --to-hex $ETH_BLOCK)
fi
ETH_BLOCK=${ETH_BLOCK:-earliest}

seth rpc eth_getLogs -- \
  -n {} -s $(seth --to-address "$1") -i address \
        -s $ETH_BLOCK -i fromBlock \
  -n [] $topics -i topics -i append
