#!/usr/bin/env bash
set -e

LAD=$1; shift
BID=$(seth --to-word $(seth --to-hex $1)); shift

p() { printf "%-4s %-52s %-10s\n" "$1" "$2" "$3"; }

case $1 in
  tick) {
    seth send $LAD 'tick(uint256)' $BID
  };;
  tend) {
    mcd --vat-hope $LAD
    lot=$(seth --to-uint256 $(seth --to-wei $2 eth))
    bid=$(seth --to-uint256 $(seth --to-wei $3 eth))
    (set -x; seth send $LAD 'tend(uint id, uint lot, uint bid)' $BID $lot $bid)
  };;
  *) {
    bid=$(seth call $LAD 'bids(uint)' $BID)
    p "bid" $(mcd --to-wad ${bid:2:64})    "Last bid amount"
    p "lot" $(mcd --to-wad ${bid:66:64})   "Lot amount"
    p "guy" 0x${bid:154:40}                "Highest bidder"
    p "tic" $(seth --to-dec ${bid:194:64}) "Bid expiry"
    p "end" $(seth --to-dec ${bid:258:64}) "Auction end"
    p "urn" 0x${bid:346:40}                "Gem surplus recipient"
    p "gal" 0x${bid:410:40}                "Dai recipient (vow)"
    p "tab" $(mcd --to-rad ${bid:450:64})  "Debt to recover"
  };;
esac
