#!/usr/bin/env bash
### mcd-bites -- Recent bites
### Usage: mcd bites [-B <block>] [--ilk=<id>] [--urn=<address>]
set -e

sig="Bite(bytes32,address,uint256,uint256,uint256,address,uint256)"
sig=$(seth keccak "$(seth --from-ascii $sig)")
[[ "$MCD_ILK" ]] && ilk=$(seth --to-bytes32 "$(seth --from-ascii "$MCD_ILK")")
[[ "$MCD_URN" ]] && urn=$(seth --to-bytes32 "$MCD_URN")
seth logs "${MCD_CAT?}" "$sig" "$ilk" "$urn" |
  while read -r log; do
    tx=$(jshon -e transactionHash -u <<<"$log")
    block=$(seth --to-dec "$(jshon -e blockNumber -u <<<"$log")")
    topics=($(jshon -e topics -a -u <<<"$log"))
    data=$(jshon -e data -u <<<"$log")

    urnAddress="0x${topics[2]:26:64}"

    # If urn flag is set, only show data for that urn
    if [[ "$MCD_URN" && "$MCD_URN" != "$urnAddress" ]]; then
      continue
    fi

    echo "ilk $(mcd --to-ascii "${topics[1]}")"
    echo "urn $urnAddress"
    echo "ink $(mcd --to-wad "${data:2:64}")"
    echo "art $(mcd --to-wad "${data:66:64}")"
    echo "tab $(mcd --to-rad "${data:130:64}")"
    echo "flipper 0x${data:218:40}"
    echo "flip $(seth --to-dec "0x${data:258:64}")"
    echo "tx: $tx";
    echo "block: $block";
    echo
  done
