#!/usr/bin/env bash
set -e

# TODO - get storage at nested

idx=$(seth --to-uint256 2) # urns slot
ilk=$(seth --to-bytes32 $(seth --from-ascii "ETH"))
urn=$(seth --to-bytes32 $ETH_FROM)
key=$(seth --to-uint256 $(seth keccak $ilk$idx))
key=$(seth keccak $urn$key)

ink=$(seth storage $MCD_VAT $key)
echo $ink
echo $(seth --to-dec $ink)
