#!/usr/bin/env bash
set -e

if [[ $MCD_PROXY = yes ]]; then
  MCD_PROXY=$(mcd --proxy-address)
fi

LAD=${MCD_PROXY:-$ETH_FROM}
case $1 in
  count) {
    sig="count(address)"
    hex=$(seth call ${CDP_MANAGER?} $sig ${LAD?})
    seth --to-dec $hex
  };;
  owner) {
    id=$(seth --to-word ${MCD_CDP?})
    sig="lads(uint256)(address)"
    echo 0x$(seth call ${CDP_MANAGER?} $sig $id)
  };;
  ls) {
    guy=0x$(seth --to-word $LAD)
    sig="NewCdp(address,address,uint256)"
    sig=$(seth keccak "$(seth --from-ascii $sig)")
    seth logs ${CDP_MANAGER?} $sig $guy |
    while read -r log; do
      id=$(seth --to-dec $(jshon -e data -u <<<"$log"))
      echo $id
      mcd --cdp=$id urn
    done
  };;
  *) {
    mcd cdp-send "$@"
  };;
esac
