#!/usr/bin/env bash
### mcd-poke -- Update the spot price for a given Ilk
### Usage: mcd --ilk=<id> poke
###
###
### Example: mcd poke ETH
set -e

ilk=$(mcd --require-ilk $0)
seth send ${MCD_SPOT?} 'poke(bytes32)' "$ilk"
[[ $SETH_ASYNC != yes ]] && mcd --ilk=$MCD_ILK ilk spot
