#!/usr/bin/env bash
cat <<.
mcd 0.2.1
dss-testchain-deploy 3b95164a2bcd5e9e8c4b1b3efaf7ff1f2d7de159

Copyright (C) 2018, 2019 dc <dc@dapp.org>

License: GNU AGPL version 3 or later <https://www.gnu.org/licenses/agpl-3.0>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.
.
