#!/usr/bin/env bash
### mcd-bite -- Trigger liquidation of an unsafe Urn
### Usage: mcd bite --ilk=<id> --urn=<index>
###
### Specify the Ilk identifier and index of the Urn to bite.
set -e

ilk=$(mcd --require-ilk)
urn=$(mcd --require-urn $0)

p() { printf "%-3s %-30s %-10s\n" "$1" "$2" "$3"; }

sig="bite(bytes32,address)(uint256)"
tx=$(seth send --async "${MCD_CAT?}" "$sig" "$ilk" "$urn")
echo >&2 -n "${0##*/}: Waiting for transaction receipt..."
block=$(SETH_TICK=true seth receipt "$tx" blockNumber)
block=$(seth --to-hex "$block")
echo >&2

sig="Bite(bytes32,address,uint256,uint256,uint256,uint256)"
keccak=$(seth keccak "$(seth --from-ascii $sig)")
logs=$(seth rpc eth_getLogs -- \
  -n {} \
    -s "${MCD_CAT?}" -i address \
    -s "$block"      -i fromBlock \
    -s "$block"      -i toBlock \
  -n [] \
    -s "$keccak" -i append \
    -s "0x$ilk"  -i append \
    -s "0x$urn"  -i append \
  -i topics \
  -i append | echo "[$(paste -sd , -)]")
data=$(echo "$logs" | jshon -a -e data -u)
hash=$(echo "$logs" | jshon -a -e transactionHash -u)

if [ "$hash" == "$tx" ]; then
  echo "$tx"
  p "id"  $(seth --to-dec 0x${data:196:64}) "Bite identifier"
  p "ink" $(mcd --to-wad ${data:2:64})      "Seized collateral ($MCD_ILK)"
  p "art" $(mcd --to-wad ${data:66:64})     "Seized debt (DAI)"
  p "tab" $(mcd --to-wad ${data:130:64})    "Outstanding debt to auction"
else
  echo >&2 "${0##*/}: Transaction failed."
  seth >&2 receipt "$tx"
  exit 1
fi
