#!/usr/bin/env bash
### mcd-join -- Add collateral to the system
### Usage: mcd join <adapter> <amount>
###
### Specify the @adapter and the amount of collateral
### to deposit.
##
### See also mcd-ls
set -e
[ $# = 2 ] || mcd --fail "$0: Missing argument(s)"

# TODO - check inputs

lad=$(>&2 seth --to-address $1) || mcd --fail "$0: Invalid adapter address $1"
wad=$(seth --to-hex $(seth --to-wei "$2 eth"))

# TODO - adapter dictionary
echo >&2 "Depositing $2 GEM"

(set -x; seth send "${lad}" "join(uint)" "$wad")
