#!/usr/bin/env bash
### mcd-frobs -- Recent frobs
### Usage: mcd frobs [-B <block>] [--ilk=<id>] [--urn=<address>]
set -e
sig="frob(bytes32,address,address,address,int256,int256)"
sig=$(seth keccak "$(seth --from-ascii $sig)")
sig=0x$(seth --to-bytes32 ${sig::10})
[[ "$MCD_ILK" ]] && ilk=0x$(seth --to-bytes32 $(seth --from-ascii "$MCD_ILK"))
[[ "$MCD_URN" ]] && urn=0x$(seth --to-bytes32 "$MCD_URN")
seth logs ${MCD_VAT?} "$sig" "$ilk" "$urn" |
  while read -r log; do
    tx=$(jshon -e transactionHash -u <<<"$log")
    block=$(seth --to-dec $(jshon -e blockNumber -u <<<"$log"))
    topics=($(jshon -e topics -a -u <<<"$log"))
    data=$(jshon -e data -u <<<"$log")

    echo "ilk $(mcd --to-ascii ${topics[1]})"
    echo "urn ${topics[2]}"
    echo "dink $(mcd --to-wad ${data:394:64})"
    echo "dart $(mcd --to-wad ${data:458:64})"
    echo "tx: $tx";
    echo "block: $block";
    echo
  done
