#!/usr/bin/env bash
params=(
  "module=logs" "action=getLogs"
  "address=$1" "fromBlock=$2" "toBlock=latest"
  "apikey=$ETHERSCAN_API_KEY"
)

[[ ! -z "$3" ]] && params[7]="topic0=$3"

if [ ! -z "$MCD_ILK" ]; then
  ilk=0x$(seth --to-bytes32 $(seth --from-ascii "$MCD_ILK"))
  params[8]="topic0_1_opr=and"
  params[9]="topic1=$ilk"
fi

query=$(printf "&%s" "${params[@]}")
response=$(seth curl "${ETHERSCAN_API_URL?}""${query/&/?}")
message=$(jshon <<<"$response" -e message -u)
result=$(jshon <<<"$response" -e result -j)
if [[ $message = OK || $result = "[]" ]]; then
  jshon <<<"$result" -a -j | mcd --decode-events
else
  echo >&2 "${0##*/}: error: $response"
  exit 1
fi
