#!/usr/bin/env bash
set -e
case $MCD_ILK in
  "ETH"*) {
    curl -sS "http://api.etherscan.io/api?module=stats&action=ethsupply${ETHERSCAN_API_KEY:+&apikey=$ETHERSCAN_API_KEY}" |
      seth --to-fix 18 "$(jq -r '.result')"
  };;
  *) {
    gem=$(seth call "$(mcd gem adapter)" 'gem()')
    sig="totalSupply()(uint256)"
    addr="$(seth --to-address "${gem:(-40)}")"
    seth call "$addr" "$sig"
  };;
esac
