#!/usr/bin/env bash
from=$(seth --to-address ${1::40})

case $MCD_ILK in
  "ETH") {
    mcd --to-wad $(seth balance $from)
  };;
  *) {
    sig="balanceOf(address)(uint)"
    mcd --to-wad $(seth call $(eval echo "\$${MCD_ILK}") "$sig" "$from")
  }
esac
