#!/usr/bin/env bash
### mcd-flap -- Trigger a flap auction
### Usage: mcd flap
###
### Trigger a flap auction if sufficient surplus Dai (Joy)
### has accumulated in the liquidator.
###
### See also mcd-vow
set -e

# TODO
# show the status of the liquidator

(set -x; seth send "${MCD_VOW}" "flap()")
