#!/usr/bin/env bash
set -e
ilk=$(mcd --require-ilk)

export SETH_ASYNC=yes

if [[ $MCD_PROXY == yes ]]; then
  export ETH_GAS=233776
  guy=$(mcd --proxy-address)
  sig="open(address,bytes32)"
  tx=$(mcd --proxy-exec $sig ${CDP_MANAGER?} $ilk)
else
  export ETH_GAS=212072
  guy=$(mcd --require-from)
  sig="open(bytes32)"
  tx=$(seth send ${CDP_MANAGER?} $sig $ilk)
fi

echo >&2 -n "${0##*/}: Waiting for transaction receipt..."
block=$(SETH_TICK=true seth receipt "$tx" blockNumber)
block=$(seth --to-hex "$block")
echo >&2
sig="NewCdp(address,address,uint256)"
sig=$(seth keccak "$(seth --from-ascii $sig)")
logs=$(seth rpc eth_getLogs -- \
    -n {} \
    -s "${CDP_MANAGER?}" -i address \
    -s "$block"          -i fromBlock \
    -s "$block"          -i toBlock \
    -n [] \
    -s "$sig"  -i append \
    -s "0x$(seth --to-word $guy)" -i append \
    -i topics \
    -i append | echo "[$(paste -sd , -)]")
hex=$(echo "$logs" | jshon -a -e data -u)
echo "Opened: cdp $(seth --to-dec $hex)"
