#!/usr/bin/env bash
### mcd-vow -- Liquidator balances
### Usage: mcd vow [<command>]
set -e

case $1 in
  Sin) {
    sin=$(seth call "${MCD_VOW}" 'Sin()(uint256)')
    echo $(mcd --to-wad "$sin")
  };;
  sin) {
    mcd vow-sin $2
  };;
  Woe) {
    woe=$(seth call "${MCD_VOW}" 'Woe()(uint256)')
    echo $(mcd --to-wad "$woe")
  };;
  Ash) {
    ash=$(seth call "${MCD_VOW}" 'Ash()(uint256)')
    echo $(mcd --to-wad "$ash")
  };;
  Awe) {
    awe=$(seth call "${MCD_VOW}" 'Awe()(uint256)')
    echo $(mcd --to-wad "$awe")
  };;
  Joy) {
    joy=$(seth call "${MCD_VOW}" 'Joy()(uint256)')
    echo $(mcd --to-wad "$joy")
  };;
  wait) {
    wait=$(seth call "${MCD_VOW}" 'wait()(uint256)')
    echo $(mcd --to-wad "$wait")
  };;
  sump) {
    sump=$(seth call "${MCD_VOW}" 'sump()(uint256)')
    echo $(mcd --to-wad "$sump")
  };;
  bump) {
    bump=$(seth call "${MCD_VOW}" 'bump()(uint256)')
    echo $(mcd --to-wad "$bump")
  };;
  hump) {
    hump=$(seth call "${MCD_VOW}" 'hump()(uint256)')
    echo $(mcd --to-wad "$hump")
  };;
  *) {
    echo "Options:"
    echo "  sin <era>"
    echo "  Sin"
    echo "  Woe"
    echo "  Ash"
    echo "  Awe"
    echo "  Joy"
    echo "  wait"
    echo "  sump"
    echo "  bump"
    echo "  hump"
  }
esac
