#!/usr/bin/env bash
set -e
[ -n "$1" ] || mcd --fail "gem: Please specify an exit amount"

urn=$(mcd --require-urn gem)
guy=$(mcd --to-address ${2:-$ETH_FROM})
wad=$(seth --to-word $(seth --to-wei $1 eth))
sig="exit(bytes32, address, uint)"
seth send $(mcd gem adapter) "$sig" "$urn" "$guy" "$wad"

[[ $SETH_ASYNC != yes ]] && mcd gem balance
