#!/usr/bin/env bash
# TODO accumulate passes and fails to report
assertBalanceChanged() {
  diff=$(echo "$1 - $2" | bc)
  numericCompare $diff $3
}

numericCompare() {
  p $(awk -v n1="${1}" -v n2="${2}" \
    'BEGIN { print (n1 == n2) ? "true" : "false" }' 2>/dev/null)
}

p() { [ $1 = "false" ] && echo "FAIL" && exit; }
